apiVersion: apps/v1
kind: Deployment
metadata:
  name: colonies-prometheus-deployment
  labels:
    app: colonies-prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: colonies-prometheus
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1 
      maxSurge: 0 
  template:
     metadata:
       annotations:
         timestamp: {{ now | quote }}
       labels:
         app: colonies-prometheus
     spec:
       initContainers:
       - name: "init-datapath"
         image: alpine:3.16.2 
         command: ["chown", "-R", "65534:65534", "/prometheus"]
         command: ["/bin/chmod","-R","777","/prometheus"]
         volumeMounts:
         - name: colonies-prometheus-storage-volume 
           mountPath: /prometheus
           subPath: ""
         {{ if .Values.PrometheusResourceLimit }}
         resources:
            limits:
              memory: {{ (.Values.PrometheusMemory | quote) }}
            requests:
              cpu: {{ (.Values.PrometheusCPU | quote) }}
              memory: {{ (.Values.PrometheusMemory | quote) }}
         {{ end }}
       containers:
       - name: colonies-prometheus
         args:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus/"
         image: {{ .Values.PrometheusImage | quote }}
         imagePullPolicy: "Always"
         {{ if .Values.PrometheusResourceLimit }}
         resources:
            limits:
              memory: {{ (.Values.PrometheusMemory | quote) }}
            requests:
              cpu: {{ (.Values.PrometheusCPU | quote) }}
              memory: {{ (.Values.PrometheusMemory | quote) }}
         {{ end }}
         ports:
           - containerPort: 9090
         volumeMounts:
          - name: colonies-prometheus-config-volume
            mountPath: /etc/prometheus/
          - name: colonies-prometheus-storage-volume
            mountPath: /prometheus/
       volumes:
         - name: colonies-prometheus-config-volume
           configMap:
             defaultMode: 420
             name: colonies-prometheus-server-conf
         - name: colonies-prometheus-storage-volume
           persistentVolumeClaim:
             claimName: colonies-prometheus-storage-pvc
